name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  REMOTE_DIR: ${{ secrets.REMOTE_REPO_DIR }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Images
        run: |
          docker build -t $DOCKERHUB_USER/fusionpact-backend:latest -f backend/Dockerfile .
          docker push $DOCKERHUB_USER/fusionpact-backend:latest
          docker build -t $DOCKERHUB_USER/fusionpact-frontend:latest -f frontend/Dockerfile .
          docker push $DOCKERHUB_USER/fusionpact-frontend:latest

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            git config --global --add safe.directory $REMOTE_DIR &&
            cd $REMOTE_DIR &&
            git pull origin main &&
            docker-compose pull &&
            docker-compose up -d --remove-orphans
            "
            